#define _GNU_SOURCE
#include <unistd.h>
#include <stdlib.h>
#include <sys/resource.h>
#include <pwd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <dirent.h>
#include <netdb.h>
#include <time.h>
#include <poll.h>
#include <locale.h>
#include <semaphore.h>
#include <sys/statvfs.h>
#include <termios.h>
#include <dlfcn.h>
#include <signal.h>
#include <sys/stat.h>
#include <sys/un.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <sys/uio.h>
#include <errno.h>
#include <pthread.h>
#include <netinet/tcp.h>
#include <sys/types.h>
#include <sys/wait.h>
