/* This file is automatically generated.
   It defines a symbol `__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.  */

#ifdef _LIBC
# error Applications may not define the macro _LIBC
#endif

#define __stub___aio_sigqueue
#define __stub___gai_sigqueue
#define __stub___mq_open_2
#define __stub_acct
#define __stub_copy_file_range
#define __stub_getdirentries
#define __stub_getdirentries64
#define __stub_getipv4sourcefilter
#define __stub_getsourcefilter
#define __stub_glob64
#define __stub_mincore
#define __stub_mq_close
#define __stub_mq_getattr
#define __stub_mq_notify
#define __stub_mq_open
#define __stub_mq_receive
#define __stub_mq_send
#define __stub_mq_setattr
#define __stub_mq_timedreceive
#define __stub_mq_timedsend
#define __stub_mq_unlink
#define __stub_msgctl
#define __stub_msgget
#define __stub_msgrcv
#define __stub_msgsnd
#define __stub_posix_fadvise
#define __stub_posix_fadvise64
#define __stub_pthread_barrierattr_setpshared
#define __stub_pthread_condattr_setpshared
#define __stub_pthread_getcpuclockid
#define __stub_pthread_mutex_getprioceiling
#define __stub_pthread_mutex_setprioceiling
#define __stub_pthread_mutexattr_getprioceiling
#define __stub_pthread_mutexattr_setprioceiling
#define __stub_pthread_rwlockattr_setpshared
#define __stub_pthread_setschedparam
#define __stub_pthread_setschedprio
#define __stub_recvmmsg
#define __stub_remap_file_pages
#define __stub_sched_get_priority_max
#define __stub_sched_get_priority_min
#define __stub_sched_getaffinity
#define __stub_sched_getparam
#define __stub_sched_rr_get_interval
#define __stub_sched_setaffinity
#define __stub_sched_setparam
#define __stub_semctl
#define __stub_semget
#define __stub_semop
#define __stub_semtimedop
#define __stub_sendmmsg
#define __stub_setipv4sourcefilter
#define __stub_setsourcefilter
#define __stub_sigqueue
#define __stub_swapoff
#define __stub_swapon
#define __stub_ustat
#define __stub_vhangup
